### ISSUE TITLE
No Cask with this name exists.

### ISSUE THREAD

**Issue by jylitalo** [tmatilai/homebrew-terraforms#217]
Both installation scenarios (that are mentioned in README) fails, even though https://github.com/Yleisradio/homebrew-terraforms/blob/master/Casks/terraform-1.7.4.rb exists.
```
% chtf 1.7.4
chtf: Terraform version 1.7.4 not found
chtf: Do you want to install it? [yN] y
chtf: Installing Terraform version 1.7.4
Warning: Cask 'terraform-1.7.4' is unavailable: No Cask with this name exists.
==> Searching for similarly named casks...
Error: No casks found for terraform-1.7.4.
% brew install --cask terraform-1.7.4
Warning: Cask 'terraform-1.7.4' is unavailable: No Cask with this name exists.
==> Searching for similarly named casks...
Error: No casks found for terraform-1.7.4.
```

**Comment by jylitalo** [comment]
I wonder if this is related to terraform license change, since https://formulae.brew.sh/formula/terraform gives 1.5.7 as latest (released September 7, 2023) and https://formulae.brew.sh/formula/opentofu gives version 1.6.2, which was released last week.

**Comment by tmatilai** [comment]
I saw the same, but haven't had time to debug it yet. 
I don't think it's licence issue, seems like Homebrew is ignoring the whole tap.

**Comment by tmatilai** [comment]
Seems that Homebrew is now more picky about the Cask formats, including the naming. #219 should fix it for the Casks, but a new `chtf` version is still required to be able to use them with it.

**Comment by tmatilai** [comment]
I'll try to adapt `chtf` next. Then we'll need to update its Formula here, and probably add some migration instructions.

**Comment by tmatilai** [comment]
This should be fixed now with the latest `chtf` version.
