### ISSUE TITLE
Update checksum for 0.11.13

### ISSUE THREAD

**Issue by carljavier** [tmatilai/homebrew-terraforms#24]
Noticed the checksum for 0.11.13 is `56b3b0313c41022e76e84f3dbf5045181f4fe3fc1005909a1cc97e6928bad35e` 

when it looks to be: 
`e9988443da39e5d81a5f7f1b6a5d97b25e2a1151d9be76cdc2e380df97e57856` 

based off https://releases.hashicorp.com/terraform/0.11.13/terraform_0.11.13_SHA256SUMS  and a local check.

**Comment by matt9949** [comment]
+1 - Can't chtf to 0.11.3 due to incorrect checksum.

**Comment by tatusl** [comment]
Thanks for spotting this @carljavier

This is now fixed with https://github.com/Yleisradio/homebrew-terraforms/pull/25

**Comment by tmatilai** [comment]
Thanks to all! They must have rebuilt the zip file. Strange.
