### ISSUE TITLE
Delete specific Terraform versions

### ISSUE THREAD

**Issue by mkozjak** [tmatilai/homebrew-terraforms#41]
Is there a way to delete installed terraform versions via `chtf`?
Or is there some other preferred way to delete those?

**Comment by tmatilai** [comment]
`chtf` itself does not support uninstalling, and I think it is best not to overload that command.

But you can uninstall the versions directly with `brew`. For example:

    brew cask uninstall terraform-0.11.12

**Comment by mkozjak** [comment]
Thanks!
