### ISSUE TITLE
chtf causes a `terraform plan` error: error while refreshing state: "No valid credential sources found for AWS Provider"

### ISSUE THREAD

**Issue by ottumm** [tmatilai/homebrew-terraforms#6]
See https://github.com/hashicorp/terraform/issues/11980 for details. I've confirmed that this error happens with terraform v0.8.8 installed via chtf but *not* terraform v0.8.8 installed via the normal brew taps.

**Comment by tmatilai** [comment]
`chtf` installs Terraform using the exact same packages as official Homebrew formula, so something else here.

And basically the only thing `chtf` does is that it sets `PATH` to include the binaries in that package. Is it possible that you have some ancient Terraform version installed somewhere? I have idea that old versions had separate binaries for different providers etc.

**Comment by tmatilai** [comment]
There is not much we can do without more specific information. I haven't seen that problem anywhere else.

I'll close the issue, but we can of course continue tracking down the problem.

**Comment by ottumm** [comment]
I finally got around to trying this out on a clean system, and you're correct: this was due to having an old Terraform version installed (before it switched to a single binary). This should remain closed. Thanks!
