### ISSUE TITLE
homebrew deprecates cask usage

### ISSUE THREAD

**Issue by spanky-medal** [tmatilai/homebrew-terraforms#71]
https://github.com/Homebrew/discussions/discussions/340

```
$ chtf 0.12.30
chtf: Installing Terraform version 0.12.30
Error: Calling brew cask install is disabled! Use brew install [--cask] instead.
```

Thanks for all your effort into this project, I love it!

**Comment by tmatilai** [comment]
Hi Tom,

This should be fixed in `chtf` [v2.1.1](https://github.com/Yleisradio/homebrew-terraforms/pull/70) with Yleisradio/chtf#8.
`brew upgrade [chtf]` should do the trick.

Thanks for your thanks! 😃

**Comment by spanky-medal** [comment]
Ah, thanks. I had upgraded but not re-sourced my .zshrc so it was still symlinked somehow:

```
$ chtf --version
chtf: 1.4.0

$ brew upgrade chtf
Updating Homebrew...
==> Auto-updated Homebrew!
Updated 3 taps (homebrew/core, homebrew/cask and homebrew/cask-fonts).
==> Updated Formulae
Updated 87 formulae.
==> New Casks
operator                                                                                                silicon
==> Updated Casks
Updated 42 casks.

Warning: yleisradio/terraforms/chtf 2.1.1 already installed

$ source ~/.oh-my-zsh/custom/spanky.zsh
$ chtf --version
chtf: 2.1.1
```

**Comment by tmatilai** [comment]
Ah yeah, good point. Bash/zsh version has to be loaded again, as the functions are stored in the shell session. (The fish version uses the shell's auto loading since v2.1.0)
