### ISSUE TITLE
Apple Silicon (arm64) versions of Terraform?

### ISSUE THREAD

**Issue by mbokman** [tmatilai/homebrew-terraforms#81]
Hello, I use chtf to manage my different terraform installations but I notice that the terraform-0.14.8 Cask only offers the Intel version of this release.

I checked https://www.terraform.io/downloads.html and don't see 0.14.8 (yet?), let alone the arm64 version but the brew terraform bottle offers the native version of 0.14.8 which I am now using via ```chtf system```.

**Comment by tmatilai** [comment]
Good catch, at least I really haven’t investigated how Brew Casks should handle arm64. If you have pointers, please share. I’ll take a look in the weekend.

This repo polls for Terraform releases directly from their distribution system, and 0.14 was found there. Also their changelog lists it, so it seems that the releases page was just not updated for some reason.

**Comment by tmatilai** [comment]
Note to myself: arm64 support should be checked also in the auto-install script in chtf

**Comment by tmatilai** [comment]
OK, so the status is that Hashicorp does not ship Terraform for `darwin_arm64` yet ([the issue](https://github.com/hashicorp/terraform/issues/27257)). It seems that they are basically just waiting for most important providers to add support.

Homebrew does build their own version from the source with their own build system, but that is not "official", and I'm not sure they keep all the old versions available. And even if they would, I still prefer to wait for the Hashicorp official releases.

But in the meanwhile, I'll to add support here so the arm64 versions are installable as soon as they are released.

**Comment by tmatilai** [comment]
The support for future darwin/arm64 releases should be prepared by #82.

But I'll leave this issue open until we confirm that everything works as expected after the first release.

**Comment by tmatilai** [comment]
Terraform v1.0.2 finally includes a build for darwin/arm64. #100 should include it also to this Cask. 

@mbokman any chance you could verify that it works as expected? 🤗

**Comment by mbokman** [comment]
@tmatilai Tested successfully:
```
$ chtf
   0.12.31
   0.13.7
   0.14.9
   0.15.5
$ chtf 1.0.2
chtf: Terraform version 1.0.2 not found
chtf: Do you want to install it? [yN] y
chtf: Installing Terraform version 1.0.2
==> Downloading https://releases.hashicorp.com/terraform/1.0.2/terraform_1.0.2_darwin_arm64.zip
######################################################################## 100.0%
==> Installing Cask terraform-1.0.2
🍺  terraform-1.0.2 was successfully installed!
$ chtf
   0.12.31
   0.13.7
   0.14.9
   0.15.5
 * 1.0.2
$ which terraform
/opt/homebrew/Caskroom/terraform-1.0.2/1.0.2/terraform
$ file `which terraform`
/opt/homebrew/Caskroom/terraform-1.0.2/1.0.2/terraform: Mach-O 64-bit executable arm64
$
```

Thanks!

**Comment by tmatilai** [comment]
Excellent, thanks a lot for reporting back!
